import type { SpeechEngine } from './speechEngine';

/**
 * Pre-recorded clip lookup. Key is the normalized `${lang}|${text.trim()}` —
 * the exact pair the app passes to `speak`/`speakText` — mapping to a bundled
 * mp3 URL (served from `public/voice/`). Generated by
 * `scripts/build-voice-clips.mjs` into `voiceClips.ts`.
 */
export type ClipIndex = Record<string, string>;

/**
 * Plays one short clip. Injectable so tests don't need a real
 * `HTMLAudioElement`. `play` MUST call `onDone` exactly once (on end, error, or
 * a rejected `play()` — never hang) and returns a `cancel()` that stops
 * playback and also settles via `onDone`.
 */
export interface AudioPlayer {
  play(url: string, onDone: () => void): () => void;
}

/**
 * Real player backed by `HTMLAudioElement`. `onDone` fires exactly once (a
 * `done` flag guards against `ended`+`error` double-firing and against
 * `cancel()` racing the natural end). `play()` is a Promise — autoplay
 * rejection still resolves so the caller never hangs. In jsdom (no `Audio`) it
 * is a safe no-op that resolves immediately.
 */
function createHtmlAudioPlayer(): AudioPlayer {
  return {
    play(url, onDone) {
      if (typeof Audio === 'undefined') {
        onDone();
        return () => {};
      }
      let done = false;
      const finish = (): void => {
        if (done) return;
        done = true;
        onDone();
      };
      const audio = new Audio(url);
      audio.addEventListener('ended', finish);
      audio.addEventListener('error', finish);
      // A rejected play() (autoplay policy) must not hang the caller.
      void audio.play().catch(finish);
      return () => {
        audio.pause();
        finish();
      };
    },
  };
}

/**
 * SpeechEngine that plays a pre-recorded clip when one exists for
 * `${lang}|${text.trim()}`, and otherwise delegates to `fallback` (Web Speech)
 * for unbounded content like child names. `AudioManager` is unchanged — this
 * engine satisfies the same `SpeechEngine` contract from GĐ4A: `onDone` fires
 * exactly once on every branch and `cancel()` settles too.
 */
export function createPrerecordedEngine(
  clips: ClipIndex,
  fallback: SpeechEngine,
  player: AudioPlayer = createHtmlAudioPlayer(),
): SpeechEngine {
  return {
    speak(text, lang, onDone) {
      const url = clips[`${lang}|${text.trim()}`];
      if (url) return player.play(url, onDone);
      // No clip → Web Speech fallback (returns its own cancel handle).
      return fallback.speak(text, lang, onDone);
    },
  };
}
